#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from petsys import daqd, config, fe_power
from copy import deepcopy
import pandas
import os
import argparse
import math
import glob

def checkRequiredArgs(parser, required_args, conditional_args):
	args, _ = parser.parse_known_args()
	if getattr(args, "enableOnlineProcessing"):
		for arg in required_args:
			if not getattr(args, arg):
				parser.error(f"--{arg} is required when --enableOnlineProcessing is set")
	if not getattr(args, "enableOnlineProcessing"):
		for arg in conditional_args:
			if getattr(args, arg):
				parser.error(f"--{arg} is not allowed when --enableOnlineProcessing is not set")


def main():
	parser = argparse.ArgumentParser(description='Acquire SIPM data from the DAQ system')
	parser.add_argument("--config", type=str, required=True, help="Configuration file")
	parser.add_argument("-o", type=str, dest="fileNamePrefix", required=True, help = "Output data filename prefix. If --enableOnlineProcessing is set, a suffix identifying the output data type will be added for the processed data output file. ")
	parser.add_argument("--time", type=float, required=True, help="Acquisition time (in seconds)")
	parser.add_argument("--mode", type=str, required=True, choices=["tot", "qdc", "mixed"], help = "Acquisition mode (tot, qdc or mixed)")
	parser.add_argument("--enable-hw-trigger", dest="hwTrigger", action="store_true", help="Enable the hardware coincidence filter")
	parser.add_argument('--enable-realtime-processing', dest="enableOnlineProcessing", action='store_true', help='Enable online (real-time) data processing.')
	parser.add_argument("--output-type", type=str, dest="outputType", required=False, choices=["raw","singles", "groups", "coincidences"], help="If --enableOnlineProcessing is set, this option selects the type output processed.\n")
	parser.add_argument("--output-format", type=str, dest="outputFormat", required=False, choices=["text", "textCompact", "binary", "binaryCompact", "root"], help="If --enableOnlineProcessing is set, this option selects the format of the output processed data.\n")
	parser.add_argument("--writeFraction", type=float, required=False, help="If --enableOnlineProcessing is set, this option selects the fraction of events (in percentage) to be written to the output file. If not set, all events are written.\n")
	parser.add_argument("--writeMultipleHits", type=int, required=False, help="If --enableOnlineProcessing is set, and outputType is 'groups' or 'coincidences', this option selects the number of hits to be written in the output file. If not set, only 1 hit (with max amplitude) is written.\n")
	parser.add_argument("--timeref", type=str, required=False, choices=["sync", "wall", "step", "user"], help="If --enableOnlineProcessing is set, this option selects the time reference for timestamps in processed data.\n")
	parser.add_argument("--writeRawData", dest="writeRaw", action="store_true", help="If --enableOnlineProcessing is set, write a raw data file in addition to the output processed data file.\n")
	parser.add_argument("--param-table", type=str, dest="paramTable", help="Table containing the name and values of 1 or 2 parameters to be scanned during data acquisition. Allowed parameters are: OV (SIPM Overvoltage), vth_t1 (t1 discriminator threshold, in DAC units relative to the channel baseline), vth_t2 (t2 discriminator threshold, in DAC units relative to the channel baseline), vth_e (e discriminator threshold, in DAC units relative to the channel baseline), disc_lsb_t1 (t1 discriminator DAC LSB)")
	parser.add_argument("--wait-on", dest="waitOn", type=str, help="Wait on named pipe before acquiring data")
	parser.add_argument("--portID",  type=int, required=False, help="Set target FEBD port ID")
	parser.add_argument("--slaveID", type=int, required=False, help="Set target FEBD slave ID")
	args = parser.parse_args()
	
	conditionalArgs = []
	requiredArgs = []
	if args.enableOnlineProcessing:
		requiredArgs = ["outputType","outputFormat"]
	else:
		conditionalArgs = ["writeRaw", "outputType","outputFormat","writeFraction","writeMultipleHits","timeref"]

	checkRequiredArgs(parser, requiredArgs, conditionalArgs)

	parser.set_defaults(writeFraction=100, writeMultipleHits=1, timeref="user", writeRaw=False)
	
	args = parser.parse_args()
		
	validParams = ["OV","vth_t1","vth_t2","vth_e","disc_lsb_t1"]

	if args.paramTable is not None:
		if not os.path.exists(args.paramTable):
			print("Error: no such file - %s" % args.paramTable)
			exit(1)
		table = pandas.read_table(args.paramTable)
		parNames = list(table)
		for name in parNames:
			if name not in validParams:
				print(("Error: Invalid parameter - %s" % name))
				exit(1)

		step1Values = list(table[parNames[0]])
		if len(parNames) == 2:
			step2Values = list(table[parNames[1]])
		elif len(parNames) == 1:
			step2Values = [0]
			parNames.append("none")
		else:
			print("Error: only two parameters can be scanned at the same time")
			exit(1)


	mask = config.LOAD_ALL
	if args.mode != "mixed":
		mask ^= config.LOAD_QDCMODE_MAP

	if not args.hwTrigger:
		mask ^= config.LOAD_FIRMWARE_QDC_CALIBRATION

	systemConfig = config.ConfigFromFile(args.config, loadMask=mask)

	conn = daqd.Connection()

	if (args.portID != None and args.slaveID != None):
		for p, s in conn.getActiveFEBDs():
			fe_power.set_fem_power(conn,p,s,"off")  
		conn.initializeSystem(power_lst = [(args.portID,args.slaveID)])
	else:
		conn.initializeSystem()
	

	systemConfig.loadToHardware(conn, bias_enable=config.APPLY_BIAS_ON, hw_trigger_enable=args.hwTrigger, qdc_mode = args.mode)

	if args.waitOn:
		conn.waitOnNamedPipe(args.waitOn)

	# if using online processing, perform a data transmission check before opening file for writing
	if not args.enableOnlineProcessing:
		conn.openRawAcquisition(args.fileNamePrefix)
	else:
		testFileName = os.path.dirname(args.fileNamePrefix)+"/checkDataTransmissionFile"
		if args.writeRaw:
			conn.openRawAcquisitionWithProcessing(testFileName,args.config, args.outputType, args.outputFormat, args.writeFraction, args.writeMultipleHits, args.timeref, verbose=False)
			if not conn.checkDataTransmission(args.time):
				exit(1)
			conn.openRawAcquisitionWithProcessing(args.fileNamePrefix,args.config, args.outputType, args.outputFormat, args.writeFraction, args.writeMultipleHits, args.timeref)
		else:
			conn.openAcquisitionWithProcessing(testFileName, args.config, args.outputType, args.outputFormat, args.writeFraction, args.writeMultipleHits, args.timeref, verbose=False)
			if not conn.checkDataTransmission(args.time):
				exit(1)
			conn.openAcquisitionWithProcessing(args.fileNamePrefix, args.config, args.outputType, args.outputFormat, args.writeFraction, args.writeMultipleHits, args.timeref)
		for file_path in glob.glob(testFileName + "*"):
			if os.path.isfile(file_path):
				os.remove(file_path)
	

	activeAsics = conn.getActiveAsics()
	activeChannels = [ (portID, slaveID, chipID, channelID) for channelID in range(64) for portID, slaveID, chipID in activeAsics ]

	asicsConfig = conn.getAsicsConfig()

	if args.paramTable is None:
		conn.acquire(args.time, 0, 0)
	else:
		for step1 in step1Values:
			step1 = float(step1)
			if math.isnan(step1):
				continue
			if parNames[0] in ['vth_t1', 'vth_t2', 'vth_e']:
				for portID, slaveID, chipID, channelID in activeChannels:
					cc = asicsConfig[(portID, slaveID, chipID)].channelConfig[channelID]
					dac_setting = systemConfig.mapAsicChannelThresholdToDAC((portID, slaveID, chipID, channelID), parNames[0], int(step1))
					cc.setValue(parNames[0], dac_setting)
			elif parNames[0] in ['disc_lsb_t1']:
				for portID, slaveID, chipID in activeAsics:
					cc = asicsConfig[(portID, slaveID, chipID)].globalConfig
					cc.setValue(parNames[0], int(step1))
			elif parNames[0] in ['OV']:
				biasVoltageConfig = conn.get_hvdac_config()
				for key in conn.getActiveBiasChannels():
					offset, prebd, bd, over__ = systemConfig.getBiasChannelDefaultSettings(key)
					vset = offset + bd + step1
					dac_setting = systemConfig.mapBiasChannelVoltageToDAC(key, vset)
					biasVoltageConfig[key] = dac_setting
					conn.set_hvdac_config(biasVoltageConfig)
			conn.setAsicsConfig(asicsConfig)

			for step2 in step2Values:
				step2 = float(step2)
				if math.isnan(step2):
					continue
				if parNames[1] in ['vth_t1', 'vth_t2', 'vth_e']:
					for portID, slaveID, chipID, channelID in activeChannels:
						cc = asicsConfig[(portID, slaveID, chipID)].channelConfig[channelID]
						dac_setting = systemConfig.mapAsicChannelThresholdToDAC((portID, slaveID, chipID, channelID), parNames[1], int(step2))
						cc.setValue(parNames[1], dac_setting)
				elif parNames[1] in ['disc_lsb_t1']:
					for portID, slaveID, chipID in activeAsics:
						cc = asicsConfig[(portID, slaveID, chipID)].globalConfig
						cc.setValue(parNames[1], int(step2))
				elif parNames[1] in ['OV']:
					#step2 = step2_
					biasVoltageConfig = conn.get_hvdac_config()
					for key in conn.getActiveBiasChannels():
						offset, prebd, bd, over__ = systemConfig.getBiasChannelDefaultSettings(key)
						vset = offset + bd + step2
						dac_setting = systemConfig.mapBiasChannelVoltageToDAC(key, vset)
						biasVoltageConfig[key] = dac_setting
					conn.set_hvdac_config(biasVoltageConfig)

				if parNames[1] == "none":
					print("Python:: Acquiring data for: " + parNames[0] + " = " + str(step1))
				else:
					print("Python:: Acquiring data for: " + parNames[0] + " = " + str(step1) + " ; " + parNames[1] + " = " + str(step2))
				conn.setAsicsConfig(asicsConfig)
				conn.acquire(args.time, float(step1), float(step2))



	systemConfig.loadToHardware(conn, bias_enable=config.APPLY_BIAS_OFF)
	return 0

if __name__ == '__main__':
	exit(main())
