#!/usr/bin/env python
# -*- coding: utf-8 -*-

from petsys import daqd, config
from copy import deepcopy
import argparse

parser = argparse.ArgumentParser(description='Make a simple SiPM bias voltage table')
parser.add_argument("--config", type=str, required=True, help="Configuration file")
parser.add_argument("--vth_t1", type=int, required=True, help="Discriminator T1 (DAC above zero)")
parser.add_argument("--vth_t2", type=int, required=True, help="Discriminator T2 (DAC above zero)")
parser.add_argument("--vth_e", type=int, required=True, help="Discriminator E (DAC above zero)")


args = parser.parse_args()
systemConfig = config.ConfigFromFile(args.config, loadMask=config.LOAD_DISC_CALIBRATION)

print "# portID\tslaveID\tchipID\tchannelID\tvth_t1\tvth_t2\tvth_e"
for portID, slaveID, chipID, channelID in systemConfig.discCalibrationTable.keys():
	print "%d\t%d\t%d\t%d\t%d\t%d\t%d" % (portID, slaveID, chipID, channelID, args.vth_t1, args.vth_t2, args.vth_e)
