#!/usr/bin/env python
# -*- coding: utf-8 -*-

from petsys import daqd, config
from copy import deepcopy
import argparse

parser = argparse.ArgumentParser(description='Make a simple SiPM bias voltage table')
parser.add_argument("--config", type=str, required=True, help="Configuration file")
parser.add_argument("--prebd", type=float, required=True, help="Pre-breakdown voltage")
parser.add_argument("--bd", type=float, required=True, help="Breakdown voltage")
parser.add_argument("--over", type=float, required=True, help="Nominal overvoltage")


args = parser.parse_args()
systemConfig = config.ConfigFromFile(args.config, loadMask=config.LOAD_AD5535_CALIBRATION)

print "# portID\tslaveID\tchannelID\tPre-breakdown\tBreakdown\tOvervoltage"
for (portID, slaveID, channelID) in systemConfig.ad5535CalibrationTable.keys():
	print "%d\t%d\t%d\t%4.2f\t%4.2f\t%4.2f" % (portID, slaveID, channelID, args.prebd, args.bd, args.over)

