#!/usr/bin/env python
#-*- coding: utf-8 -*-
#

from petsys import daqd
from time import sleep
import sys

daqd = daqd.Connection()

print "--- DAQ PORTS ---" 
for portID in daqd.getActivePorts():
	print "DAQ Port %2d: " % portID, "%12d transmitted %12d received (%d errors)" % daqd.getPortCounts(portID)

print "--- CONNECTED UNITSs ---"
for portID, slaveID in daqd.getActiveUnits():
	mtx, mrx, mrxBad, slaveOn, stx, srx, srxBad = daqd.getFEBDCount1(portID, slaveID)
	if daqd.read_config_register(portID, slaveID, 1, 0x0000) == 1:
		unitType = "FEB/D"
	elif daqd.read_config_register(portID, slaveID, 1, 0x0001) == 1:
		unitType = "CLK&TRIGGER"
	else:
		sys.stderr.write("ERROR: UNIT (%2d, %2d) is of unknown type!\n" % (portID, slaveID))
		exit(1)

	print "Unit (%2d, %2d): %s\n" % (portID, slaveID, unitType),
	print "  MASTER link %12d transmitted %12d received (%d errors)" % (mtx, mrx, mrxBad)
	if slaveOn:
		print "  SLAVE  link %12d transmitted %12d received (%d errors)" % (stx, srx, srxBad)
	else:
		print "  SLAVE  link off"
