#!/usr/bin/env python3
#-*- coding: utf-8 -*-
#

from petsys import daqd, info
from time import sleep
import sys
import pandas as pd

daqd = daqd.Connection()



daq_stats = []
for portID in daqd.getActivePorts():
#	print("DAQ Port %2d: " % portID, "%12d transmitted %12d received (%d errors)" % daqd.getPortCounts(portID))
	daq_stats.append((
		portID,
		*daqd.getPortCounts(portID)
	))

print("--- DAQ PORTS ---")
daq_stats = pd.DataFrame(
	columns = [ "portID", "tx", "rx", "rx_errors" ],
	data = daq_stats
)

print(daq_stats)

unit_stats = []
for portID, slaveID in daqd.getActiveUnits():
	unit_up_counter = daqd.read_config_register(portID, slaveID, 64, 0x02D8) * 5E-9
	pll_up = daqd.read_config_register(portID, slaveID, 1, 0x0200) == 1
	if pll_up:
		pll_up_counter = daqd.read_config_register(portID, slaveID, 64, 0x02E0) / daqd.getSystemFrequency()
		time_tag = daqd.read_config_register(portID, slaveID, 46, 0x0203) / daqd.getSystemFrequency()
	else:
		pll_up_counter = -1
		time_tag = -1

	mup = daqd.read_config_register(portID, slaveID, 64, 0x0470) * 5E-9
	sup = daqd.read_config_register(portID, slaveID, 64, 0x0478) * 5E-9

	mtx, mrx, mrxBad, slaveOn, stx, srx, srxBad = daqd.getFEBDCount1(portID, slaveID)
	slaveOn = slaveOn != 0
	if not slaveOn:
		sup, stx, srx, srxBad = -1, -1, -1, -1

	base_pcb, fw_variant, prom_variant = daqd.getUnitInfo(portID, slaveID)
	unit_version = "0x%016X" % daqd.read_config_register(portID, slaveID, 64, 0xFFF0)

	if info.is_febd((base_pcb, fw_variant, prom_variant)):
		unit_type = "FEB/D"

	elif info.is_trigger((base_pcb, fw_variant, prom_variant)):
		unit_type = "CLK&TGR"
	else:
		sys.stderr.write("ERROR: UNIT (%2d, %2d) is of unknown type!\n" % (portID, slaveID))
		exit(1)

	unit_type = f"{unit_type} {base_pcb:04X}/{fw_variant:016X}"

	unit_stats.append((
		portID, slaveID,
		unit_type,
		unit_version,
		unit_up_counter,
		pll_up, pll_up_counter, time_tag,
		mup, mtx, mrx, mrxBad,
		slaveOn, sup, stx, srx, srxBad
		))

unit_stats = pd.DataFrame(
	columns = [
		"portID", "slaveID", "unit_type", "fw_version",
		"uptime", "sysclk_up", "sysclk_uptime", "sysclk_timetag",
		"mlink_uptime", "mlink_tx", "mlink_rx", "mlink_rx_errors",
		"slink_up", "slink_uptime", "slink_tx", "slink_rx", "slink_rx_errors" ],
	data = unit_stats
)

pd.set_option('display.max_columns', 100)
pd.set_option('display.width', 1000)
print("--- CONNECTED UNITSs ---")
print(unit_stats)
